services:
  jitsi:
    build: .
    container_name: jitsi
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    working_dir: /app/packages/app
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install -g npm@11.6.2 && npm start"
    networks:
      - jitsi-network

networks:
  jitsi-network:
    driver: bridge